---
- name: Set restic_url
  set_fact:
    restic_url: 'https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ _platform_map[ansible_architecture] | default(ansible_architecture) }}.bz2'
  when: restic_url == ''

- name: Download client binary
  get_url:
    url: '{{ restic_url }}'
    dest: '{{ restic_path }}/restic.bz2'
    force: True
  register: get_url_restic

- name: Decompress the binary
  shell: "bzip2 -dc {{ get_url_restic.dest }} > {{ restic_path }}/restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ _platform_map[ansible_architecture] }}"
  args:
    creates: '{{ restic_path }}/restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ _platform_map[ansible_architecture] }}'

- name: Ensure permissions are correct
  file:
    path: '{{ restic_path }}/restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ _platform_map[ansible_architecture] }}'
    mode: '0755'
    owner: '{{ restic_dir_owner }}'
    group: '{{ restic_dir_group }}'
